handle SIGTERM by stopping all running services
perk11/large-model-proxy pull request #2
Opened 2024-07-21 21:13 UTC by lun-4

currently, the behavior on SIGTERM is to exit ourselves but still leave all child processes running. this patch changes the behavior to actively catch SIGTERM and so, gracefully shutdown the services (by sending SIGTERM to them, waiting 2 seconds, then SIGKILL).

the TODO comment regarding wait-until-SIGKILL is left as more of a suggestion, if that's welcome I can submit that in a separate PR.

2024-07-21 21:19 UTC, perk11 commented
Thank you for the PR, it didn't happen in my testing, but maybe I was sending some other signal. I will test it tonight

2024-07-21 21:24 UTC, lun-4 commented
I double checked that behavior against main branch, without my patch, and it does shutdown the child processes... oops. I was checking some weird interactions against the proxy and podman and wanted to explicitly catch the incoming SIGTERM so I know it is actually being sent to a certain PID rather than depending on some other runtime behavior to do it (this patch would still be likely useful in a future where we use better heuristics to figure out if something is actually shutdown and the relevant VRAM is free)

2024-07-22 03:09 UTC, perk11 requested changes
Thanks, I was able to take a better look, and this is definitely something worth doing. Sending SIGKILL right away in stopService() was not the right choice, and specifically handling SIGTERM and SIGINT should make it more reliable.

Let me know if you'd like to address the 2 comments I left, or if I not I can take a crack at it.

2024-07-22 03:09 UTC, perk11 commented on main.go
> +		time.Sleep(2 * time.Second)
This seems like it would introduce a delay any time when stopping a service, not just when receiving SIGTERM. And most services will probably be able to terminate way before 2s have passed. Before merging this I'd like to rework this to check if the PID has finished every 50ms, to avoid slowing down starting new services by 2s every time.

I think it should be possible to check by using `runningService.cmd.ProcessState == nil`, as cmd.ProcessState should get populated on process exit. If this doesn't work, there is also an option of sending `kill -0 PID` to check

2024-07-22 03:09 UTC, perk11 commented on main.go
> +	signal.Notify(exit, os.Interrupt, syscall.SIGTERM)
Maybe the same behavior should happen on SIGINT?

2024-07-22 04:29 UTC, perk11 requested changes
Thanks for the update, just one more minor comment, and I will test this shortly

2024-07-22 04:29 UTC, perk11 commented on main.go
> +			log.Printf("Received SIGTERM, stopping all services")
The signal name here could also be SIGINT now, can this message be updated to include the actual signal name? Or if that's hard, maybe something like "Received interrupting signal, stopping all services"?

2024-07-22 05:07 UTC, merged

2024-07-22 05:07 UTC, perk11 commented
I tested this, and it works well, I'll fix the message separately

2024-07-22 06:32 UTC, perk11 commented
@lun-4 On a closer inspection, runningService.cmd.ProcessState was always nil, seems like it doesn't get automatically populated after sending a signal, so this was always exiting immediately (and the right check would've been `processState != nil`), but that wasn't working anyway. I reworked the waiting code a bit: https://github.com/perk11/large-model-proxy/commit/d1c4afe388627b4154d84b4f122b7689c3be0a4b calling process.Wait() seems to do the trick.

2024-07-22 06:35 UTC, lun-4 commented
oh I see, thanks for the note (and the merge), just tested it myself and seems to work as well, will keep the technique in mind whenever I'm polling a PID in the future!